#!/bin/bash
# Usage: brightness [percentage]
# Changes the brightness of the monitor to match the percentage argument of this
# script, it will require sudo privledges

print-help-message ()
{
  echo "Usage: brightness [percentage]"
  echo ""
  echo " - percentage: must be an integer in [0,100]"
}

input=${1}
max_brightness_file="/sys/class/backlight/intel_backlight/max_brightness"

# Test for an input
if [ -z "${input}" ]; then
  echo "Error: No arguments"
  print-help-message
  exit 1
fi

# Test for the standard --help/-h arguments
if [ "${input}" == "--help" -o "${input}" == "-h" ]; then
  print-help-message
  exit 0
fi

# Test whether the argument is a number at all
if ! [[ "${input}" =~ ^[0-9]+$ ]]; then
  echo "Error: Argument is not a number"
  print-help-message
  exit 1
fi

# Test if the number is within the permitted range
if ! [ "${input}" -ge 0 -a "${input}" -le 100 ]; then
  echo "Error: Argument is out of range"
  print-help-message
  exit 1
fi

# Additional safety measures, shouldn't be necessary
if [ $input -gt 100 ]; then
  percentage=100
else
  if [ $input -lt 0 ]; then
    percentage=1
  else
    percentage=$input
  fi
fi

# Test if the file containing the max brightness exists
# Exit the script if it doesn't as this signals that the
# system probably determines brightness differently
if [ ! -f "${max_brightness_file}" ]; then
  echo "Error: Brightness settings on system not consistent with this script"
  exit 1
fi

typeset -i max_brightness=$(cat ${max_brightness_file})
new_brightness=$((max_brightness * percentage / 100))

echo $new_brightness | sudo tee /sys/class/backlight/intel_backlight/brightness
